### ISSUE TITLE
Issues with Valve.lib

### ISSUE THREAD

**Issue by evanshultz** [KiCad/kicad-symbols#1253] opened 2018-12-11 16:27 UTC
From https://github.com/KiCad/kicad-symbols/pull/1247.

```
Checking symbol 'ECH81':
  Violating S4.1
    Pin requirements
    Pins not located on 100mil (=2.54mm) grid:
     - Pin A (8), @ (0, 550)mil
     - Pin G2_G4 (1), @ (300, 150)mil
     - Pin G1 (2), @ (-300, -150)mil
     - Pin A (6), @ (0, 550)mil
     - Pin G3 (7), @ (-300, 50)mil
     - Pin K_G5 (~), @ (-100, -450)mil
     - Pin F1 (4), @ (-100, -550)mil
     - Pin F2 (5), @ (100, -550)mil
  Violating S5.1
    For components with a single default footprint, footprint field is filled with valid footprint
    filename
    Footprint filter 'VALVE*NOVAL*P*' does not match the footprint 'Valve:Valve_Noval_P' set for this symbol.
     - could not match 'Valve_Noval_P' against filter 'VALVE*NOVAL*P*'
     - could not match 'Valve:Valve_Noval_P' against filter 'VALVE*NOVAL*P*'
Changed symbol 'Valve.lib:EC92'
Checking symbol 'EC92':
  Violating S3.1
    Origin is centered on the middle of the symbol
    Symbol not centered on origin
     - Center calculated @ (-100, 0)
  Violating S4.1
    Pin requirements
    Pins not located on 100mil (=2.54mm) grid:
     - Pin F1 (3), @ (-100, -350)mil
     - Pin F2 (4), @ (100, -350)mil
  Violating S5.1
    For components with a single default footprint, footprint field is filled with valid footprint
    filename
    Footprint filter 'VALVE*MINI*P*' does not match the footprint 'Valve:Valve_Mini_P' set for this symbol.
     - could not match 'Valve_Mini_P' against filter 'VALVE*MINI*P*'
     - could not match 'Valve:Valve_Mini_P' against filter 'VALVE*MINI*P*'
Changed symbol 'Valve.lib:EL84'
Checking symbol 'EL84':
  Violating S3.1
    Origin is centered on the middle of the symbol
    > Symbol slightly off-center
    >   Center calculated @ (0, 25)
  Violating S4.1
    Pin requirements
    Pins not located on 100mil (=2.54mm) grid:
     - Pin G1 (2), @ (-300, -50)mil
     - Pin K_G3 (3), @ (-100, -350)mil
     - Pin A (7), @ (0, 450)mil
     - Pin G2 (9), @ (300, 50)mil
  Violating S5.1
    For components with a single default footprint, footprint field is filled with valid footprint
    filename
    Footprint filter 'VALVE*NOVAL*P*' does not match the footprint 'Valve:Valve_Noval_P' set for this symbol.
     - could not match 'Valve_Noval_P' against filter 'VALVE*NOVAL*P*'
     - could not match 'Valve:Valve_Noval_P' against filter 'VALVE*NOVAL*P*'
Changed symbol 'Valve.lib:CK6418'
Checking symbol 'CK6418':
  Violating S3.1
    Origin is centered on the middle of the symbol
    > Symbol slightly off-center
    >   Center calculated @ (0, 50)
  Violating S5.1
    For components with a single default footprint, footprint field is filled with valid footprint
    filename
    Footprint filter 'VALVE*MINI*PENTODE*LINEAR*' does not match the footprint 'Valve:Valve_Mini_Pentode_Linear' set for this symbol.
     - could not match 'Valve_Mini_Pentode_Linear' against filter 'VALVE*MINI*PENTODE*LINEAR*'
     - could not match 'Valve:Valve_Mini_Pentode_Linear' against filter 'VALVE*MINI*PENTODE*LINEAR*'
  Violating S6.3
    Part meta-data is filled in as appropriate
    ALIAS CK548DX has metadata errors:
     - Missing all fields on 'Properties > Description' tab
Changed symbol 'Valve.lib:EM84'
Checking symbol 'EM84':
  Violating S3.1
    Origin is centered on the middle of the symbol
    > Symbol slightly off-center
    >   Center calculated @ (0, 25)
  Violating S4.1
    Pin requirements
    Pins not located on 100mil (=2.54mm) grid:
     - Pin K (2), @ (-100, -350)mil
     - Pin L (6), @ (0, 450)mil
  Violating S5.1
    For components with a single default footprint, footprint field is filled with valid footprint
    filename
    Footprint filter 'VALVE*NOVAL*P*' does not match the footprint 'Valve:Valve_Noval_P' set for this symbol.
     - could not match 'Valve_Noval_P' against filter 'VALVE*NOVAL*P*'
     - could not match 'Valve:Valve_Noval_P' against filter 'VALVE*NOVAL*P*'
Changed symbol 'Valve.lib:EABC80'
Checking symbol 'EABC80':
  Violating S3.1
    Origin is centered on the middle of the symbol
    Symbol not centered on origin
     - Center calculated @ (-100, 0)
  Violating S4.1
    Pin requirements
    Pins not located on 100mil (=2.54mm) grid:
     - Pin F1 (4), @ (-100, -350)mil
     - Pin F2 (5), @ (100, -350)mil
  Violating S5.1
    For components with a single default footprint, footprint field is filled with valid footprint
    filename
    Footprint filter 'VALVE*NOVAL*P*' does not match the footprint 'Valve:Valve_Noval_P' set for this symbol.
     - could not match 'Valve_Noval_P' against filter 'VALVE*NOVAL*P*'
     - could not match 'Valve:Valve_Noval_P' against filter 'VALVE*NOVAL*P*'
Changed symbol 'Valve.lib:ECL86'
Checking symbol 'ECL86':
  Violating S4.1
    Pin requirements
    Pins not located on 100mil (=2.54mm) grid:
     - Pin F1 (4), @ (-100, -375)mil
     - Pin F2 (5), @ (100, -375)mil
  Violating S5.1
    For components with a single default footprint, footprint field is filled with valid footprint
    filename
    Footprint filter 'VALVE*NOVAL*P*' does not match the footprint 'Valve:Valve_Noval_P' set for this symbol.
     - could not match 'Valve_Noval_P' against filter 'VALVE*NOVAL*P*'
     - could not match 'Valve:Valve_Noval_P' against filter 'VALVE*NOVAL*P*'
Changed symbol 'Valve.lib:ECC81'
Checking symbol 'ECC81':
  Violating S3.1
    Origin is centered on the middle of the symbol
    Symbol not centered on origin
     - Center calculated @ (-100, -25)
  Violating S4.1
    Pin requirements
    Pins not located on 100mil (=2.54mm) grid:
     - Pin F1 (4), @ (-100, -450)mil
     - Pin F1 (5), @ (100, -450)mil
     - Pin F2 (9), @ (0, -450)mil
  Violating S5.1
    For components with a single default footprint, footprint field is filled with valid footprint
    filename
    Footprint filter 'VALVE*NOVAL*P*' does not match the footprint 'Valve:Valve_Noval_P' set for this symbol.
     - could not match 'Valve_Noval_P' against filter 'VALVE*NOVAL*P*'
     - could not match 'Valve:Valve_Noval_P' against filter 'VALVE*NOVAL*P*'
Changed symbol 'Valve.lib:EL34'
Checking symbol 'EL34':
  Violating S3.1
    Origin is centered on the middle of the symbol
    > Symbol slightly off-center
    >   Center calculated @ (0, 25)
  Violating S4.1
    Pin requirements
    Pins not located on 100mil (=2.54mm) grid:
     - Pin G3 (1), @ (300, 150)mil
     - Pin A (3), @ (0, 450)mil
     - Pin G2 (4), @ (300, 50)mil
     - Pin G1 (5), @ (-300, -50)mil
     - Pin F1 (8), @ (-100, -350)mil
  Violating S5.1
    For components with a single default footprint, footprint field is filled with valid footprint
    filename
    Footprint filter 'VALVE*OCTAL*' does not match the footprint 'Valve:Valve_Octal' set for this symbol.
     - could not match 'Valve_Octal' against filter 'VALVE*OCTAL*'
     - could not match 'Valve:Valve_Octal' against filter 'VALVE*OCTAL*'
Changed symbol 'Valve.lib:ECL82'
Checking symbol 'ECL82':
  Violating S3.1
    Origin is centered on the middle of the symbol
    > Symbol slightly off-center
    >   Center calculated @ (0, -13)
  Violating S4.1
    Pin requirements
    Pins not located on 100mil (=2.54mm) grid:
     - Pin F1 (4), @ (-100, -425)mil
     - Pin F2 (5), @ (100, -425)mil
  Violating S5.1
    For components with a single default footprint, footprint field is filled with valid footprint
    filename
    Footprint filter 'VALVE*NOVAL*P*' does not match the footprint 'Valve:Valve_Noval_P' set for this symbol.
     - could not match 'Valve_Noval_P' against filter 'VALVE*NOVAL*P*'
     - could not match 'Valve:Valve_Noval_P' against filter 'VALVE*NOVAL*P*'
Changed symbol 'Valve.lib:ECC88'
Checking symbol 'ECC88':
  Violating S3.1
    Origin is centered on the middle of the symbol
    Symbol not centered on origin
     - Center calculated @ (-100, -25)
  Violating S4.1
    Pin requirements
    Pins not located on 100mil (=2.54mm) grid:
     - Pin F1 (4), @ (-100, -450)mil
     - Pin F2 (5), @ (100, -450)mil
  Violating S5.1
    For components with a single default footprint, footprint field is filled with valid footprint
    filename
    Footprint filter 'VALVE*NOVAL*P*' does not match the footprint 'Valve:Valve_Noval_P' set for this symbol.
     - could not match 'Valve_Noval_P' against filter 'VALVE*NOVAL*P*'
     - could not match 'Valve:Valve_Noval_P' against filter 'VALVE*NOVAL*P*'
Changed symbol 'Valve.lib:STABI'
Checking symbol 'STABI':
  Violating S5.1
    For components with a single default footprint, footprint field is filled with valid footprint
    filename
    Footprint filter 'VALVE*GLIMM*' does not match the footprint 'Valve:Valve_Glimm' set for this symbol.
     - could not match 'Valve_Glimm' against filter 'VALVE*GLIMM*'
     - could not match 'Valve:Valve_Glimm' against filter 'VALVE*GLIMM*'
  Violating S6.3
    Part meta-data is filled in as appropriate
    Component STABI has metadata errors:
     - Missing all fields on 'Properties > Description' tab
Changed symbol 'Valve.lib:EF80'
Checking symbol 'EF80':
  Violating S3.1
    Origin is centered on the middle of the symbol
    > Symbol slightly off-center
    >   Center calculated @ (0, 25)
  Violating S4.1
    Pin requirements
    Pins not located on 100mil (=2.54mm) grid:
     - Pin G1 (2), @ (-300, -50)mil
     - Pin S (6), @ (300, -150)mil
     - Pin A (7), @ (0, 450)mil
     - Pin G2 (8), @ (300, 50)mil
     - Pin G3 (9), @ (300, 150)mil
    Pin F1 (3) @ (-100,-400) length (130mils) is not a multiple of 50mils
    Pin F1 (4) @ (-100,-400) length (130mils) is not a multiple of 50mils
    Pin F2 (5) @ (100,-400) length (130mils) is not a multiple of 50mils
  Violating S5.1
    For components with a single default footprint, footprint field is filled with valid footprint
    filename
    Footprint filter 'VALVE*NOVAL*P*' does not match the footprint 'Valve:Valve_Noval_P' set for this symbol.
     - could not match 'Valve_Noval_P' against filter 'VALVE*NOVAL*P*'
     - could not match 'Valve:Valve_Noval_P' against filter 'VALVE*NOVAL*P*'
  Violating S6.3
    Part meta-data is filled in as appropriate
    ALIAS EF85 has metadata errors:
     - Missing all fields on 'Properties > Description' tab
Changed symbol 'Valve.lib:EF83'
Checking symbol 'EF83':
  Violating S3.1
    Origin is centered on the middle of the symbol
    > Symbol slightly off-center
    >   Center calculated @ (0, 25)
  Violating S4.1
    Pin requirements
    Pins not located on 100mil (=2.54mm) grid:
     - Pin G2 (1), @ (300, 50)mil
     - Pin K (3), @ (-100, -350)mil
     - Pin A (6), @ (0, 450)mil
     - Pin S (7), @ (300, -150)mil
     - Pin G3 (8), @ (300, 150)mil
     - Pin G1 (9), @ (-300, -50)mil
  Violating S5.1
    For components with a single default footprint, footprint field is filled with valid footprint
    filename
    Footprint filter 'VALVE*NOVAL*P*' does not match the footprint 'Valve:Valve_Noval_P' set for this symbol.
     - could not match 'Valve_Noval_P' against filter 'VALVE*NOVAL*P*'
     - could not match 'Valve:Valve_Noval_P' against filter 'VALVE*NOVAL*P*'
  Violating S6.3
    Part meta-data is filled in as appropriate
    ALIAS EF86 has metadata errors:
     - Missing all fields on 'Properties > Description' tab
```

**Comment by antoniovazquezblanco** [comment] 2019-06-27 09:15
Given https://github.com/KiCad/kicad-symbols/issues/217 and knowing that https://github.com/KiCad/kicad-symbols/issues/217#issuecomment-473954688 is more recent than the report in this issue I am going to close this as a duplicate of that thread.

Thank you for the report.

**Closed by antoniovazquezblanco** 2019-06-27 09:15 UTC
Labels: Bug, Good first issue, Help wanted, KLC issue
